### ISSUE TITLE
require backpack as a dependency

### ISSUE THREAD

**Issue by pxpm** [maurohmartinez/backpack-compare-operation#4]
https://github.com/maurohmartinez/backpack-compare-operation/blob/5986b11b163eac57d3ba17c82302e147329a5d5f/composer.json#L7

Backpack already has supported Laravel versions and PHP versions. No need to explicitly define them. If this operation only works in backpack, it's easier if you just add `backpack/crud: ^6.0` as the composer dependency 👍

**Comment by maurohmartinez** [comment]
Thanks! Done :)
